//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.04 at 05:25:19 PM CST 
//


package us.mn.state.dot.tms.server.comm.ttip.serializers.dmsStatus;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}phase1Line1"/>
 *         &lt;element ref="{}phase1Line2"/>
 *         &lt;element ref="{}phase1Line3"/>
 *         &lt;element ref="{}phase2Line1"/>
 *         &lt;element ref="{}phase2Line2"/>
 *         &lt;element ref="{}phase2Line3"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @author Dan Rossiter
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "phase1Line1",
    "phase1Line2",
    "phase1Line3",
    "phase2Line1",
    "phase2Line2",
    "phase2Line3"
})
public class DmsCurrentMessage {

    @XmlElement(name = "phase1Line1", required = true)
    protected String phase1Line1;
    @XmlElement(name = "phase1Line2", required = true)
    protected String phase1Line2;
    @XmlElement(name = "phase1Line3", required = true)
    protected String phase1Line3;
    @XmlElement(name = "phase2Line1", required = true)
    protected String phase2Line1;
    @XmlElement(name = "phase2Line2", required = true)
    protected String phase2Line2;
    @XmlElement(name = "phase2Line3", required = true)
    protected String phase2Line3;

    /**
     * Gets the value of the phase1Line1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhase1Line1() {
        return phase1Line1;
    }

    /**
     * Sets the value of the phase1Line1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhase1Line1(String value) {
        this.phase1Line1 = value;
    }

    /**
     * Gets the value of the phase1Line2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhase1Line2() {
        return phase1Line2;
    }

    /**
     * Sets the value of the phase1Line2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhase1Line2(String value) {
        this.phase1Line2 = value;
    }

    /**
     * Gets the value of the phase1Line3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhase1Line3() {
        return phase1Line3;
    }

    /**
     * Sets the value of the phase1Line3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhase1Line3(String value) {
        this.phase1Line3 = value;
    }

    /**
     * Gets the value of the phase2Line1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhase2Line1() {
        return phase2Line1;
    }

    /**
     * Sets the value of the phase2Line1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhase2Line1(String value) {
        this.phase2Line1 = value;
    }

    /**
     * Gets the value of the phase2Line2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhase2Line2() {
        return phase2Line2;
    }

    /**
     * Sets the value of the phase2Line2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhase2Line2(String value) {
        this.phase2Line2 = value;
    }

    /**
     * Gets the value of the phase2Line3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhase2Line3() {
        return phase2Line3;
    }

    /**
     * Sets the value of the phase2Line3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhase2Line3(String value) {
        this.phase2Line3 = value;
    }

}
