//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.04 at 05:25:19 PM CST 
//


package us.mn.state.dot.tms.server.comm.ttip.serializers.dmsStatus;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}dmsListDeviceStatus"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @author Dan Rossiter
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dmsListDeviceStatus"
})
public class LocalResponseGroup {

    @XmlElementWrapper(name = "dmsListDeviceStatus", required = true)
    @XmlElement(name = "dmsDeviceStatus")
    protected List<DmsDeviceStatus> dmsListDeviceStatus;

    /**
     * Gets the value of the dmsListDeviceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link List&lt;DmsDeviceStatus&gt; }
     *     
     */
    public List<DmsDeviceStatus> getDmsListDeviceStatus() {
        return dmsListDeviceStatus;
    }

    /**
     * Sets the value of the dmsListDeviceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link List&lt;DmsDeviceStatus&gt; }
     *     
     */
    public void setDmsListDeviceStatus(List<DmsDeviceStatus> value) {
        this.dmsListDeviceStatus = value;
    }

}
