//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.04 at 05:10:00 PM CST 
//


package us.mn.state.dot.tms.server.comm.ttip.serializers.cctvInventory;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;

import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}cCTVInventory" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 * @author Dan Rossiter
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class LocalResponseGroup {

    @XmlElement(name = "cCTVInventory", required = true)
    protected List<CctvInventory> cctvInventory;

    /**
     * Gets the value of the cctvInventory property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cctvInventory property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCCTVInventory().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CctvInventory }
     *
     *
     */
    public List<CctvInventory> getCCTVInventory() {
        if (cctvInventory == null) {
            cctvInventory = new ArrayList<CctvInventory>();
        }
        return this.cctvInventory;
    }

}
