//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.04 at 05:10:00 PM CST 
//


package us.mn.state.dot.tms.server.comm.ttip.serializers.cctvInventory;

import us.mn.state.dot.tms.server.comm.ttip.serializers.common.GeoLocationPoint;
import us.mn.state.dot.tms.server.comm.ttip.serializers.common.Head;
import us.mn.state.dot.tms.server.comm.ttip.serializers.common.InformationResponse;
import us.mn.state.dot.tms.server.comm.ttip.serializers.common.Location;
import us.mn.state.dot.tms.server.comm.ttip.serializers.common.MessageHeader;
import us.mn.state.dot.tms.server.comm.ttip.serializers.common.ResponseGroup;
import us.mn.state.dot.tms.server.comm.ttip.serializers.common.ResponseGroups;
import us.mn.state.dot.tms.server.comm.ttip.serializers.common.Sender;
import us.mn.state.dot.tms.server.comm.ttip.serializers.common.TimeStamp;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the us.mn.state.dot.tms.server.comm.ttip.serializers package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 *
 * @author Dan Rossiter
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Date_QNAME = new QName("", "date");
    private final static QName _CctvUrl_QNAME = new QName("", "cctv-url");
    private final static QName _NodeId_QNAME = new QName("", "node-id");
    private final static QName _CctvOther_QNAME = new QName("", "cctv-other");
    private final static QName _DeviceName_QNAME = new QName("", "device-name");
    private final static QName _Latitude_QNAME = new QName("", "latitude");
    private final static QName _MessageID_QNAME = new QName("", "messageID");
    private final static QName _IssuingAgency_QNAME = new QName("", "issuingAgency");
    private final static QName _DeviceId_QNAME = new QName("", "device-id");
    private final static QName _AgencyIdentifier_QNAME = new QName("", "agencyIdentifier");
    private final static QName _AgencyName_QNAME = new QName("", "agencyName");
    private final static QName _OrganizationId_QNAME = new QName("", "organization-id");
    private final static QName _CctvImage_QNAME = new QName("", "cctv-image");
    private final static QName _Time_QNAME = new QName("", "time");
    private final static QName _Id_QNAME = new QName("", "id");
    private final static QName _OrganizationName_QNAME = new QName("", "organization-name");
    private final static QName _Longitude_QNAME = new QName("", "longitude");
    private final static QName _ResponseTo_QNAME = new QName("", "responseTo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: us.mn.state.dot.tms.server.comm.ttip.serializers
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Head }
     * 
     */
    public Head createHead() {
        return new Head();
    }

    /**
     * Create an instance of {@link GeoLocationPoint }
     * 
     */
    public GeoLocationPoint createGeoLocationPoint() {
        return new GeoLocationPoint();
    }

    /**
     * Create an instance of {@link CctvInventory }
     * 
     */
    public CctvInventory createCCTVInventory() {
        return new CctvInventory();
    }

    /**
     * Create an instance of {@link OrganizationInformation }
     * 
     */
    public OrganizationInformation createOrganizationInformation() {
        return new OrganizationInformation();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link RouteDesignator }
     * 
     */
    public RouteDesignator createRouteDesignator() {
        return new RouteDesignator();
    }

    /**
     * Create an instance of {@link ResponseGroups }
     * 
     */
    public ResponseGroups createResponseGroups() {
        return new ResponseGroups();
    }

    /**
     * Create an instance of {@link ResponseGroup }
     * 
     */
    public ResponseGroup createResponseGroup() {
        return new ResponseGroup();
    }

    /**
     * Create an instance of {@link LocalResponseGroup }
     * 
     */
    public LocalResponseGroup createLocalResponseGroup() {
        return new LocalResponseGroup();
    }

    /**
     * Create an instance of {@link MessageHeader }
     * 
     */
    public MessageHeader createMessageHeader() {
        return new MessageHeader();
    }

    /**
     * Create an instance of {@link Sender }
     * 
     */
    public Sender createSender() {
        return new Sender();
    }

    /**
     * Create an instance of {@link TimeStamp }
     * 
     */
    public TimeStamp createTimeStamp() {
        return new TimeStamp();
    }

    /**
     * Create an instance of {@link InformationResponse }
     * 
     */
    public InformationResponse<LocalResponseGroup> createInformationResponse() {
        return new InformationResponse<LocalResponseGroup>();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date")
    public JAXBElement<Integer> createDate(Integer value) {
        return new JAXBElement<Integer>(_Date_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cctv-url")
    public JAXBElement<String> createCctvUrl(String value) {
        return new JAXBElement<String>(_CctvUrl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "node-id")
    public JAXBElement<String> createNodeId(String value) {
        return new JAXBElement<String>(_NodeId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cctv-other")
    public JAXBElement<String> createCctvOther(String value) {
        return new JAXBElement<String>(_CctvOther_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "device-name")
    public JAXBElement<String> createDeviceName(String value) {
        return new JAXBElement<String>(_DeviceName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "latitude")
    public JAXBElement<Integer> createLatitude(Integer value) {
        return new JAXBElement<Integer>(_Latitude_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "messageID")
    public JAXBElement<Long> createMessageID(Long value) {
        return new JAXBElement<Long>(_MessageID_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "issuingAgency")
    public JAXBElement<String> createIssuingAgency(String value) {
        return new JAXBElement<String>(_IssuingAgency_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "device-id")
    public JAXBElement<Short> createDeviceId(Short value) {
        return new JAXBElement<Short>(_DeviceId_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "agencyIdentifier")
    public JAXBElement<String> createAgencyIdentifier(String value) {
        return new JAXBElement<String>(_AgencyIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "agencyName")
    public JAXBElement<String> createAgencyName(String value) {
        return new JAXBElement<String>(_AgencyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "organization-id")
    public JAXBElement<Short> createOrganizationId(Short value) {
        return new JAXBElement<Short>(_OrganizationId_QNAME, Short.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cctv-image")
    public JAXBElement<String> createCctvImage(String value) {
        return new JAXBElement<String>(_CctvImage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "time")
    public JAXBElement<Integer> createTime(Integer value) {
        return new JAXBElement<Integer>(_Time_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Byte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id")
    public JAXBElement<Byte> createId(Byte value) {
        return new JAXBElement<Byte>(_Id_QNAME, Byte.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "organization-name")
    public JAXBElement<String> createOrganizationName(String value) {
        return new JAXBElement<String>(_OrganizationName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "longitude")
    public JAXBElement<Integer> createLongitude(Integer value) {
        return new JAXBElement<Integer>(_Longitude_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "responseTo")
    public JAXBElement<Long> createResponseTo(Long value) {
        return new JAXBElement<Long>(_ResponseTo_QNAME, Long.class, null, value);
    }

}
