//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.04 at 05:25:56 PM CST 
//


package us.mn.state.dot.tms.server.comm.ttip.serializers.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}pointName"/>
 *         &lt;element ref="{}linearReferencePoint"/>
 *         &lt;element ref="{}geoLocationPoint"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @author Dan Rossiter
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pointName",
    "geoLocationPoint"
})
public class PointLocation {

    @XmlElement(name = "pointName")
    protected String pointName;
    @XmlElement(name = "geoLocationPoint", required = true)
    protected GeoLocationPoint geoLocationPoint;

    /**
     * Gets the value of the pointName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointName() {
        return pointName;
    }

    /**
     * Sets the value of the pointName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointName(String value) {
        this.pointName = value;
    }

    /**
     * Gets the value of the geoLocationPoint property.
     * 
     * @return
     *     possible object is
     *     {@link GeoLocationPoint }
     *     
     */
    public GeoLocationPoint getGeoLocationPoint() {
        return geoLocationPoint;
    }

    /**
     * Sets the value of the geoLocationPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoLocationPoint }
     *     
     */
    public void setGeoLocationPoint(GeoLocationPoint value) {
        this.geoLocationPoint = value;
    }

}
