//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.04 at 05:25:19 PM CST 
//


package us.mn.state.dot.tms.server.comm.ttip.serializers.common;

import us.mn.state.dot.tms.server.comm.ttip.serializers.dmsStatus.LocalResponseGroup;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}responseGroup"/>
 *         &lt;element ref="{}localResponseGroup"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * @author Dan Rossiter
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseGroup",
    "localResponseGroup"
})
public class ResponseGroups<TLocalResponseGroup> {

    @XmlElement(name = "responseGroup", required = true)
    protected ResponseGroup responseGroup;

    // TODO: Following will not work once multiple feeds are being
    // parsed. Need an alternative to hard-coding type.
    @XmlElement(name = "localResponseGroup", required = true, type = LocalResponseGroup.class)
    protected TLocalResponseGroup localResponseGroup;

    /**
     * Gets the value of the responseGroup property.
     *
     * @return
     *     possible object is
     *     {@link ResponseGroup }
     *
     */
    public ResponseGroup getResponseGroup() {
        return responseGroup;
    }

    /**
     * Sets the value of the responseGroup property.
     *
     * @param value
     *     allowed object is
     *     {@link ResponseGroup }
     *
     */
    public void setResponseGroup(ResponseGroup value) {
        this.responseGroup = value;
    }

    /**
     * Gets the value of the localResponseGroup property.
     *
     * @return
     *     possible object is
     *     {@link TLocalResponseGroup }
     *
     */
    public TLocalResponseGroup getLocalResponseGroup() {
        return localResponseGroup;
    }

    /**
     * Sets the value of the localResponseGroup property.
     *
     * @param value
     *     allowed object is
     *     {@link TLocalResponseGroup }
     *
     */
    public void setLocalResponseGroup(TLocalResponseGroup value) {
        this.localResponseGroup = value;
    }

}
